#分号后面需要添加一个空格
server:
  port: 8080
  tomcat:
    max-threads: 20
    max-connections: 10000
  servlet:
    context-path: /demo

spring:
  #  autoconfigure:
  #    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  thymeleaf:
    cache: false
  datasource:
    #    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    #    url: jdbc:mysql://192.168.2.211:6603/bookinfo?serverTimezone=UTC
    url: jdbc:mysql://192.168.1.211:6603/bookinfo?serverTimezone=UTC
    #    url: jdbc:mysql://10.0.0.7:6603/bookinfo?serverTimezone=UTC
    #    url: jdbc:mysql://172.17.0.2:3306/bookinfo?serverTimezone=UTC
    #    username: root
    username: newuser2
    #    password: fm9>mysql
    password: fm9>MySQL
    hikari:
      maximum-pool-size: 10
      max-lifetime: 1770000
    initialization-mode: embedded
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
  #    schema:
  #    data:
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #  artemis:
  #    host: artemis.tacocloud.com
  #    port: 61617
  #    user: tacoweb
  #    password: l3tm31n
  #  jms:
  #    template:
  #      default-destination: tacocloud.order.queue
  #  rabbitmq:
  #    host: rabbit.tacocloud.com
  #    port: 5673
  #    username: tacoweb
  #    password: l3tm31n
  #    template:
  #      exchange: tacocloud.orders
  #      routing-key: kitchens.central
  #      receive-timeout: 30000
  #  kafka:
  #    template:
  #      default-topic: tacocloud.orders.topic
  #    bootstrap-servers:
  #    - kafka.tacocloud.com:9092
  #    - kafka.tacocloud.com:9093
  #    - kafka.tacocloud.com:9094
  redis:
    database: 0
    #    host: 192.168.2.211
    host: 10.0.0.7
    port: 6379
    password:
    jedis:
      pool:
        max-active: 20
        max-idle: 8
        min-idle: 0
    timeout: 5000
  application:
    name: sample-spring-redis
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: validate
#      naming:
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
logging:
  #  path: E:logspath\logs\
  file: demo.log
  level:
    root: info
#  path: logspath/logs
#    org:
#      springframework:
#        security: DEBUG

#greeting:
#  welcome: ${spring.application.name}
greeting:
  welcome: You are using ${spring.application.name}

taco:
  orders:
    pageSize: 10

mybatis:
  type-aliases-package: com.example.demo.domain
  #  mapper-locations: classpath*:**/mappers/*.xml
  mapper-locations: classpath*:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    log-prefix: mybatis-log-prefix
management:
  endpoints:
    web:
      exposure:
        include: "*"